name: Scan code with Snyk

on:
  push:
  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Snyk to check for code vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # No se continua si existen vulnerabilidades
        env:
          SNYK_TOKEN: ${{ secrets.SNYK }}
        with:
          command: code test # Escaneo del código
          args: --sarif-file-output=snykcode.sarif --all-projects

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true #  No se continua si existen vulnerabilidades
        env:
          SNYK_TOKEN: ${{ secrets.SNYK }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects 
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snykcode.sarif

      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
